steps:
  AdminGroupNopass:
    enabled: true

  Essentials:
    enabled: true

  Ntp:
    enabled: true

  Nsswitch:
    enabled: true

  PamMkhomedir:
    enabled: true

  GoogleChromeInstall:
    enabled: true

  JetbrainsToolbox:
    enabled: true

  JokerDns:
    enabled: false

  Insomnia:
    enabled: true

  SdkmanJavaInstall:
    enabled: true

  SdkmanMavenInstall:
    enabled: true

  ExtendSuspend:
    enabled: true

  DockerInstall:
    enabled: true

  DockerGroup:
    enabled: true

  DockerDataRoot:
    enabled: true

  GitPrompt:
    enabled: true

  NisServer:
    enabled: false

  DebianMirror:
    enabled: false

  NvidiaDriverInstall:
    enabled: false

  EspReplicate:
    enabled: false

  Jellyfin:
    enabled: false

  SambaShares:
    enabled: false

  NfsServer:
    enabled: false

  Shorewall:
    enabled: false
